### ISSUE TITLE
JWT in api.yaml file 

### ISSUE THREAD

**Issue by srlopez** [KarimJedda/connexion_jwt_example#1]
Hi Karim!
Great Job!
Really good stuff!

I am trying to add your code to a list of end points and i want to set security in yaml file adding this

> security:
> - $ref: '#/securityDefinitions/jwt'

before the paths section,
and remove the decorator `@jwt_required()` from the function that server the resources.

Is it possible? How? What is the syntax for that? 

I just recived this error message validating the api.yaml

> File "~/.pyenv/versions/miserver/lib/python2.7/site-packages/jsonschema/validators.py", line 123, in validate
>     raise error
> swagger_spec_validator.common.SwaggerValidationError: 'apiKey' is not of type u'array'
> 
> Failed validating u'type' in schema[u'properties'][u'security'][u'items'][u'additionalProperties']:
>     {u'items': {u'type': u'string'},
>      u'type': u'array',
>      u'uniqueItems': True}
> 
> On instance[u'security'][0]['type']:
>     'apiKey'

**Comment by KarimJedda** [comment]
Hi there @srlopez , I didn't quite understand this question man sorry. What do you mean?

**Comment by srlopez** [comment]
Sorry @KarimJedda ,
He believed it was possible to choose one of the following options the secure the api:
1. Write the decorator in each secure function, or
2. Write a $ref: '#/securityDefinitions/jwt'  reference in the api ymal file to safety in a group of endpoints

But i think i can't do that.
All secure functions need the decorator, isn't it?

**Comment by KarimJedda** [comment]
Yes exactly, that's how flask does it as I understood.

**Comment by srlopez** [comment]
Thanks again.
Closed issue

**Comment by KarimJedda** [comment]
You're welcome bro!

**Comment by srlopez** [comment]
Hi @KarimJedda 
How to define the `curl -POST http://localhost:9878/auth -H "Content-Type:application/json" -d '{"username":"user1", "password": "abcxyz"}'` in the yaml file, to get the KEY?

I think is useful  in the web page for test purpose, instead of changing from console to web page, and requery a new KEY each time the server has to restart

**Comment by KarimJedda** [comment]
Hi @srlopez , well this is something I am trying to address in the API's I'm currently designing. The easy way would be to have a '/authentication' route in your swagger yaml, that calls a function with those two variables (username, password), and give you the token back. 

This way you can also version your authentication routes etc... I don't know if it's good practice though.
I hope that was clear enough
